spring:
  application:
    name: USER_SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  mvc:
    log-request-details: true

logging:
  level:
    root: warn
    org:
      springframework:
        web: DEBUG
      hibernate: error
  file:
    name: user.log
  pattern:
    file: "%d{yyyy-MM-dd } [%thread] %-5level %logger{36} -  %msg%n"





